### ISSUE TITLE
Mit or GPL license

### ISSUE THREAD

**Issue by hekar** [dreamerslab/node.extend#23]
I am a little confused about the licensing. The link to the jQuery license makes no mention of the GPL: https://jquery.org/license/

What exactly does the dual licensing entail? Could this project be effectively treated as MIT?

**Comment by ljharb** [comment]
When any project is licensed under multiple licenses, you can pick any of those licenses and ignore the others. I believe jQuery was originally released under both, which means this code retains the GPL licensing from that time. jQuery is now only MIT, but that doesn't affect this project.

**Comment by BMillsVT** [comment]
@ljharb The link you provided in the readme file lists JQuery as being Apache 2.0 licensed (https://jquery.org/license/).  JQuery's license may have changed since you posted the link, but it's a little confusing as it's written now because there isn't any context as to why the link is provided.  Regardless, I plan on treating your software as MIT (at my choice).  But you may want to remove the link or provide some clarification.
